CREATE TABLE IF NOT EXISTS `hwid_info` (
	`HWID` VARCHAR(100) NOT NULL DEFAULT '',
	`Account` VARCHAR(45) NOT NULL DEFAULT '',
	`PlayerID` INT NOT NULL DEFAULT 0,
	`LockType` VARCHAR(20) NOT NULL DEFAULT 'NONE',
	PRIMARY KEY (`HWID`)
);
