#brproject
#Tue Sep 15 20:16:29 GMT-03:00 2026
AcceptNewGameServer=False
AutoCreateAccounts=False
DiscordChallengeSecret=brproject_discord_secret_2026_challenge_key
DiscordChallengeTimeoutSeconds=60
DiscordLoginEnabled=false
DiscordProofPublicKey=
DiscordServerId=brproject-2026
EnableFail2Ban=false
EnableFloodProtection=True
EnableNativeProxy=false
FastConnectionLimit=5
FastConnectionTime=3
Hostname=*
Login=
LoginBlockAfterBan=600
LoginHostname=127.0.0.1
LoginPort=9014
LoginServerInternalPort=2107
LoginTryBeforeBan=5
LoginserverHostname=*
LoginserverPort=2106
MaxConnectionPerIP=50
NormalConnectionTime=2
Password=
Proxy=False
ShowConnect=False
ShowLicence=True
URL=jdbc\:sqlite\:data/brproject.db
sql.login=
sql.password=
sql.url=jdbc\:sqlite\:data/brproject.db
